### ISSUE TITLE
Error compiling:  unknown field 'flock' specified in initializer

### ISSUE THREAD

**Issue by kmeekva** [mpartel/bindfs#40]
I am getting an error trying to compile on CENTOS 6.8 box.

root@rhea:/opt/bindfs/bindfs-1.13.2# make
make  all-recursive
make[1]: Entering directory `/opt/bindfs/bindfs-1.13.2'
Making all in src
make[2]: Entering directory `/opt/bindfs/bindfs-1.13.2/src'
gcc -DHAVE_CONFIG_H -I. -I..  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse    -O2 -Wall -g -O2 -MT bindfs.o -MD -MP -MF .deps/bindfs.Tpo -c -o bindfs.o bindfs.c
bindfs.c:1382: error: unknown field ‘flock’ specified in initializer
bindfs.c:1382: warning: initialization from incompatible pointer type
bindfs.c: In function ‘main’:
bindfs.c:2234: error: ‘struct fuse_operations’ has no member named ‘flock’
make[2]: *** [bindfs.o] Error 1
make[2]: Leaving directory `/opt/bindfs/bindfs-1.13.2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/opt/bindfs/bindfs-1.13.2'
make: *** [all] Error 2

Any suggestions on how to work around this?

**Comment by mpartel** [comment]
Should be fixed with [1.13.3](http://bindfs.org/downloads/bindfs-1.13.3.tar.gz) where I made it compile with FUSE 2.8.x again, but without support for `--enable-lock-forwarding`.

Thanks for reporting!
