### ISSUE TITLE
bindfs won't build on freebsd 10.3 or 11

### ISSUE THREAD

**Issue by eshagh** [mpartel/bindfs#51]
```make  all-recursive
Making all in src
cc -DHAVE_CONFIG_H -I. -I..  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DFUSE_USE_VERSION=26 -I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64   -Wall -g -O2 -MT bindfs.o -MD -MP -MF .dep
s/bindfs.Tpo -c -o bindfs.o bindfs.c
In file included from bindfs.c:56:
/usr/include/sys/file.h:210:2: error: unknown type name 'u_int'
        u_int   xf_flag;        /* flags (see fcntl.h) */
        ^
bindfs.c:1090:15: warning: implicit declaration of function 'flock' is invalid in C99 [-Wimplicit-function-declaration]
    int res = flock(fi->fh, op);
              ^
1 warning and 1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /tmp/bindfs-1.13.6/src
*** Error code 1

Stop.
make[1]: stopped in /tmp/bindfs-1.13.6
*** Error code 1

Stop.
```

appears to have started with 1.13.2 as 1.13.1 compiles without modification

**Comment by mpartel** [comment]
Thanks, git head should compile on FreeBSD again. I'm still working on getting the test suite to pass on FreeBSD.
