### PR TITLE
Fix CI (alternative to #161, fixes #163 and #165)

### LINKED ISSUE #163: macOS install fails with with `use of undeclared identifier 'DT_LNK'` after `v1.18.0`
**Problem**
running `make` after `./configure` on `macOS` throws this error referencing [src/bindfs.c](./src/bindfs.c)
```
bindfs.c:888:57: error: use of undeclared identifier 'DT_LNK'
```

The change to include `DT_LNK` was introduced in https://github.com/mpartel/bindfs/pull/160
```diff
- if (settings.resolve_symlinks && (st.st_mode & S_IFLNK) == S_IFLNK) {
+ if ((settings.resolve_symlinks && de->d_type == DT_LNK) || readdirplus) {
```

**Steps to reproduce**
macOS version: `15.4.1 (24E263)`
```bash
# install fuse-t
brew install macos-fuse-t/homebrew-cask/fuse-t

# clone 
git clone https://github.com/mpartel/bindfs.git
cd bindfs 

# install
export FUSE_CFLAGS="-I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64"
export FUSE_LIBS="-L/usr/local/lib -lfuse-t -pthread"
./autogen.sh
./configure
make # ❌ failure here
sudo make install
```

**Potential fix**
Falling back to a `S_ISLINK` check when `DTLNK` is missing seems to fix the problem. Seems like it's worthwhile to keep the `DT_LNK` check if it's supported to avoid the syscall. I will submit a PR with the changes that are working for me.
```c
#ifdef DT_LNK
        bool is_symlink = de->d_type == DT_LNK;
#else
        bool is_symlink = S_ISLNK(st.st_mode);
#endif
```

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #163 and #165
Alternative to #161

Likely not all details are perfect here yet and potentially controversial, but reverting selected commits via `git revert <sha1>` later would be easy and green CI is critical.

CC @mpartel

### CODE REVIEW

File: configure.ac [hunk 1]
```diff
@@ -37,7 +37,14 @@ AM_CONDITIONAL([INSTALL_MACOS_FS_LINK], [case $build_os in darwin* ) test x"$ena
 # _DARWIN_BETTER_REALPATH fixes MacOS realpath() broken around Catalina (#83).
 my_CPPFLAGS="-D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_XOPEN_SOURCE=700 -D__BSD_VISIBLE=1 -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_DARWIN_BETTER_REALPATH"
 
-my_CFLAGS="-std=c99 -Wall -Wextra -Wpedantic -fno-common"
+dnl libfuse >=3.17 started requiring gnu11 from the C compiler
+AS_IF([test "x$with_fuse2" == "xyes"], [
```
Comment (thesamesam) [inline configure.ac:41]: `==` is not POSIX shell, and `configure` scripts run w/ `/bin/sh` shebang, so we need:
```suggestion
AS_IF([test "x$with_fuse2" = "xyes"], [
```

Comment (hartwork) [reply configure.ac:41]: @thesamesam good point! I copy-pasted from further down, this needs fixing in multiple (existing) places:

```console
# git --no-pager grep == configure.ac
configure.ac:if test x"$enable_debug_output" == "xyes" ; then
configure.ac:if test x"$with_core_foundation" == "xyes" ; then
configure.ac:AS_IF([test "x$with_fuse2" == "xyes"], [
configure.ac:AS_IF([test "x$with_fuse2" == "xyes"],
configure.ac:    [AS_IF([test "x$with_fuse3" == "xyes"],
configure.ac:        [AS_IF([test "x$with_fuse_t" == "xyes"],
```

And then CI could run configure with Dash to expose issues like that before introduction. Actually that's something I should consider doing in multiple other projects also.

Comment (thesamesam) [reply configure.ac]: Ubuntu and Debian build their `dash` with `LINENO` disabled so that GNU Autoconf's `configure` detects that `LINENO` is missing and it'll fallback to bash.

Comment (hartwork) [reply configure.ac]: > Ubuntu and Debian build their `dash` with `LINENO` disabled so that GNU Autoconf's `configure` detects that `LINENO` is missing and it'll fallback to bash.

@thesamesam tu be sure I'm reading this right: are you saying that autoconf will put a Bash shebang line into `configure` in that case?

> However, this said, configure "errors" that manifest with non-bash are usually non-fatal anyway, just result in warnings and misdetection of features.

Understood, so it will not be waterproof and just detect some issues but not all.

Comment (hartwork) [reply configure.ac]: > Ubuntu and Debian build their `dash` with `LINENO` disabled so that GNU Autoconf's `configure` detects that `LINENO` is missing and it'll fallback to bash.

@thesamesam update: I found…

```console
$ head -n1 configure
#! /bin/sh
```

… with image `ubuntu-24.04` in GitHub Actions. From what you said, I was expecting to see Bash. Did I misunderstand?

Comment (thesamesam) [reply configure.ac]: The shebang is always `#!/bin/sh`. If `configure` detects that the running shell lacks `LINENO`, it will re-exec with bash.

Comment (hartwork) [reply configure.ac]: @thesamesam interesting. I'm reading that as "running through Dash would help on systems building Dash with LINENO support but not elsewhere, which includes Debian and Ubuntu."

**Comment by mpartel** [comment]
I _think_ I've now included all relevant fixes from here. Thanks!
