### ISSUE TITLE
1.18.1 breaks fuse (not macfuse) support on macOS

### ISSUE THREAD

**Issue by Aleksanaa** [mpartel/bindfs#169]
The commit https://github.com/mpartel/bindfs/commit/3293dc98e37eed0fb0cbfcbd40434d3c37c69480 breaks building against fuse (https://github.com/libfuse/libfuse) on macOS, throwing

```
bindfs.c:1794:19: error: incompatible function pointer types initializing 'int (*)(const char *, const char *, const char *, size_t, int, uint32_t)' (aka 'int (*)(const char *, const char *, const char *, unsigned long, int, unsigned int)') with an expression of type 'int (const char *, const char *, const char *, size_t, int)' (aka 'int (const char *, const char *, const char *, unsigned long, int)') [-Wincompatible-function-pointer-types]
 1794 |     .setxattr   = bindfs_setxattr,
      |                   ^~~~~~~~~~~~~~~
bindfs.c:1795:19: error: incompatible function pointer types initializing 'int (*)(const char *, const char *, char *, size_t, uint32_t)' (aka 'int (*)(const char *, const char *, char *, unsigned long, unsigned int)') with an expression of type 'int (const char *, const char *, char *, size_t)' (aka 'int (const char *, const char *, char *, unsigned long)') [-Wincompatible-function-pointer-types]
 1795 |     .getxattr   = bindfs_getxattr,
      |                   ^~~~~~~~~~~~~~~
```

Reverting that commit resolves the issue.

**Comment by barracuda156** [comment]
Yes, it has to be reverted for it to compile.
