### ISSUE TITLE
macOS install fails with with `use of undeclared identifier 'DT_LNK'` after `v1.18.0`

### ISSUE THREAD

**Issue by walteh** [mpartel/bindfs#163]
**Problem**
running `make` after `./configure` on `macOS` throws this error referencing [src/bindfs.c](./src/bindfs.c)
```
bindfs.c:888:57: error: use of undeclared identifier 'DT_LNK'
```

The change to include `DT_LNK` was introduced in https://github.com/mpartel/bindfs/pull/160
```diff
- if (settings.resolve_symlinks && (st.st_mode & S_IFLNK) == S_IFLNK) {
+ if ((settings.resolve_symlinks && de->d_type == DT_LNK) || readdirplus) {
```

**Steps to reproduce**
macOS version: `15.4.1 (24E263)`
```bash
# install fuse-t
brew install macos-fuse-t/homebrew-cask/fuse-t

# clone 
git clone https://github.com/mpartel/bindfs.git
cd bindfs 

# install
export FUSE_CFLAGS="-I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64"
export FUSE_LIBS="-L/usr/local/lib -lfuse-t -pthread"
./autogen.sh
./configure
make # ❌ failure here
sudo make install
```

**Potential fix**
Falling back to a `S_ISLINK` check when `DTLNK` is missing seems to fix the problem. Seems like it's worthwhile to keep the `DT_LNK` check if it's supported to avoid the syscall. I will submit a PR with the changes that are working for me.
```c
#ifdef DT_LNK
        bool is_symlink = de->d_type == DT_LNK;
#else
        bool is_symlink = S_ISLNK(st.st_mode);
#endif
```

**Comment by walteh** [comment]
I found a better solution that didn't involve any changes to the code, turns out the `FUSE_CFLAGS` and `FUSE_LIBS` environment variables are case sensitive and NEED to be `fuse_CFLAGS` and `fuse_LIBS` and I had to add `-D_DARWIN_C_SOURCE` to the `fuse_CFLAGS`.

So to install I am using: 
```zsh
export fuse_CFLAGS="-I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64 -D_DARWIN_C_SOURCE"
export fuse_LIBS="-L/usr/local/lib -lfuse-t -pthread"

./autogen.sh
./configure --with-fuse2
make
sudo make install
```

**Comment by udance4ever** [comment]
thank you so much for getting to the bottom of this!

just a heads up I had to use `-lfuse` (not `-lfuse-t`) (which technically is what is documented for `fuse_LIBS` in the [comment you referenced](https://github.com/mpartel/bindfs/issues/100#issuecomment-870699085)):
```
export fuse_CFLAGS="-I/usr/local/include/fuse -D_FILE_OFFSET_BITS=64 -D_DARWIN_C_SOURCE"
export fuse_LIBS="-L/usr/local/lib -lfuse -pthread"

./autogen.sh
./configure --with-fuse2
make
sudo make install
```

It is possible this is a function of using a [kext-less version of fuse-t](https://github.com/macos-fuse-t/fuse-t) (which works awesome for `squashfuse` too!)

**Comment by hartwork** [comment]
@mpartel could re-open this as unfixed please? To my understanding this needs some form of `-D_DARWIN_C_SOURCE` or `#define DT_LNK 10` or or … in bindfs to fix this for everyone without patching on their side.

**Comment by mpartel** [comment]
Should be fixed now, thanks!
